TYPE = @{ "boolean" | "blob" | "string" | "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" | "f32" | "f64" }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

point_type = { TYPE ~ WHITESPACE? ~ "|"? }

point = { WHITESPACE* ~ "-" ~ WHITESPACE? ~ identifier ~ ":" ~ WHITESPACE? ~ point_type* }
identifier = { (ASCII_ALPHA_LOWER | ASCII_DIGIT | "_")* }
namespace = { identifier ~ "{" ~ WHITESPACE* ~ (namespace | point)* ~ WHITESPACE* ~ "}" }


root = _{ SOI ~ namespace* ~ EOI }
